server:
  # Port number (https = 443, http = 80)
  port: 0
  # HTTPS
#  ssl:
#    key-store: keystore.p12
#    key-store-password: password
#    key-store-type: PKCS12
#    key-alias: tomcat
  # Allow requests sent during shutdown to be processed
  shutdown: GRACEFUL

spring:  lifecycle:    timeout-per-shutdown-phase: "20s"
    
eureka:  client:
    region: region-1    service-url:
      zone1: http://localhost:8761/eureka
    availability-zones:      region-1: zone1  instance:    prefer-ip-address: true

# Actuator
management:  server:    port: 9000