spring:  application:    name: eureka-discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false    region: region-1    service-url:      zone1: http://localhost:8761/eureka    availability-zones:      region-1: zone1
server:  port: 8761